routes/web.php
Route::get('/historial', 'GuestController@historial')->name('guest.historial');
//vista de historial de clientes
Route::get('/micuenta', 'GuestController@micuenta')->name('guest.micuenta');
//vista de historial de clientes
Route::get('/buscarDetallePedido', 'GuestController@buscarDetallePedido')->name('guest.buscarDetallePedido');
//enviar comprobante en historia
Route::post('/agregarComprobacion', 'GuestController@agregarComprobacion')->name('guest.agregarComprobacion');
//autocompletar buscador en header
Route::post('autocompletarInput', 'GuestController@autocompletarInput')->name('guest.autocompletarInput');
Auth::routes();

Route::resource('/shop', 'ShopController');
Route::get('/get-chunk-products', 'ShopController@getChunk')->name('shop.get.chunk');
Route::get('/shop/{id}', 'ShopController@show')->name('shop.producto');

Route::get('/shop/categorias/{id}', 'ShopController@categorias')->name('shop.categorias');

Route::get('/shop/subcategorias/{id}', 'ShopController@subcategorias')->name('shop.subcategorias');

Route::get('/shop/marcas/{id}', 'ShopController@marcas')->name('shop.marcas');

Route::get('/premium', 'ShopController@premium')->name('shop.premium');

Route::get('/lanzamientos', 'ShopController@lanzamientos')->name('shop.lanzamientos');

Route::get('/ofertas', 'ShopController@ofertas')->name('shop.ofertas');

Route::get('/busqueda', 'ShopController@genero')->name('shop.genero');
// Actualizar caja de imagenes en shop productos unitarios
Route::get('BuscarShopGenero/{genero}', 'ShopController@BuscarShopGenero')->name('shop.BuscarShopGenero');
// Actualizar caja de imagenes en shop productos para genero y id_subcategorias
Route::get('BuscarShopGeneroMain/{genero}/{id}', 'ShopController@BuscarShopGeneroMain')->name('shop.BuscarShopGeneroMain');
// Actualizar caja de imagenes en shop productos unitarios
Route::get('busqueda_imagenes/{color}/{productos}', 'ShopController@BuscarImagenes');


//Shop Olimpia
Route::get('/TiendaOlimpia', 'ShopController@tiendaOlimpia')->name('shop.tiendaOlimpia');


//Carrito
Route::get('/cart/show', 'ShopController@sesion');
//agregar item al carrito
Route::get('cart/add/{id}','ShopController@add');
//buscar producto para front.php
Route::get('busquedaProductos','GuestController@buscarProducto')->name('guest.buscarProducto');
//agregar carrito por ajax desde vista de productos
Route::get('agregarCarrito', 'ShopController@agregarCarrito')->name('carrito.agregarCarrito');
//remover carrito por ajax desde vista de productos
Route::get('removerItemCarrito', 'ShopController@removerItemCarrito')->name('carrito.removerItemCarrito');
//vista de contactos
Route::resource('/contactos', 'ContactosController');

Route::resource('/carrito', 'CarritoController');

Route::resource('/caja', 'CajaController');
//realizar pedido
Route::post('/agregarFactura', 'CajaController@agregarFactura')->name('caja.agregarFactura');
//buscar ultima factura
Route::get('/buscarFacturaLast', 'CajaController@buscarFacturaLast')->name('caja.buscarFacturaLast');
//buscar factura para desplegar en vista
Route::get('/buscarFactura', 'CajaController@buscarFactura')->name('caja.buscarFactura');
//agregar direccion de envio
Route::post('/direccionEnvio', 'CajaController@direccionEnvio')->name('caja.direccionEnvio');
//buscar ultima factura
Route::get('/buscarDireccionEnvioLast', 'CajaController@buscarDireccionEnvioLast')->name('caja.buscarDireccionEnvioLast');
//buscar direccion de envio para vista de caja
Route::get('/buscarDireccionEnvio', 'CajaController@buscarDireccionEnvio')->name('caja.buscarDireccionEnvio');
//realizar pedido
Route::post('/realizarPedido', 'CajaController@realizarPedido')->name('caja.realizarPedido');
//realizar pedido
Route::get('/pedidoFinalizado', 'CajaController@pedidoFinalizado')->name('caja.pedidoFinalizado');
//vista terminos y condiciones
Route::get('/terminos_y_condiciones', 'GuestController@terminosCondiciones')->name('guest.terminosCondiciones');
//vista nosotros
Route::get('/nosotros', 'GuestController@nosotros')->name('guest.nosotros');
//vista trabaje con nosotros
Route::get('/trabaje_con_nosotros', 'GuestController@trabajeConNosotros')->name('guest.trabajeConNosotros');
//Busqueda de requisitos de empleo 
Route::get('/buscarEmpleo', 'GuestController@buscarEmpleo')->name('guest.buscarEmpleo');

Route::post('/agregarEmpleoGuest', 'GuestController@agregarEmpleoGuest')->name('guest.agregarEmpleoGuest');

Route::get('exportacion', 'GuestController@vistaExportacion')->name('guest.vistaExportacion');

Route::post('agregarExportacion', 'GuestController@agregarExportacion')->name('guest.agregarExportacion');


Route::group(['middleware' => ['auth']], function () {

  Route::post('/editar-datos', 'GuestController@editar_datos')->name('guest.editar.datos');

  //buscar detalle de pedido
  Route::get('/enviarDetalle', 'HomeController@enviarDetalle')->name('admin.enviarDetalle');
  //buscar comprobante de pedido
  Route::get('/enviarComprobante', 'HomeController@enviarComprobante')->name('admin.enviarComprobante');
  //descargar pdf de detalle
  Route::post('/descargar-pdf', 'HomeController@descargarPDF')->name('admin.descargarDetallesPDF');
  //modificar proceso
  Route::get('/modificarProceso', 'HomeController@modificarProceso')->name('admin.modificarProceso');

  Route::post('logout', 'Auth\LoginController@logout')->name('logout');
  //front
  Route::resource('/usuario', 'UsuarioController');
  //categorias
  Route::resource('/categorias', 'CategoriasController');
  // Actualizar tabla despues de insercion de categorias
  Route::get('tabla_categorias', 'CategoriasController@categoriaBuscar');
  //subcategorias
  Route::resource('/subcategorias', 'SubCategoriasController');
  // Actualizar tabla despues de insercion de subcategorias
  Route::get('tabla_subcategorias', 'SubCategoriasController@subcategoriaBuscar');
  //Marcas
  Route::resource('/marcas', 'MarcasController');
  //Productos
  Route::resource('/productos', 'ProductosController');
  // Actualizar tabla despues de insercion de subcategorias
  Route::get('tabla_marcas', 'MarcasController@MarcasBuscar');

  Route::resource('/color', 'ColorController');
  // Actualizar tabla despues de insercion de subcategorias
  Route::get('tabla_color', 'ColorController@ColorBuscar');

  Route::post('/agregarColor', 'ProductosController@agregarColor')->name('productos.agregarColor');

  Route::resource('/talles', 'TallesController');
  // Actualizar tabla despues de insercion de subcategorias
  Route::get('tabla_talles', 'TallesController@TallesBuscar');

  Route::resource('/secciones', 'SeccionesController');
  // Actualizar tabla despues de insercion de subcategorias
  Route::get('tabla_secciones', 'SeccionesController@SeccionesBuscar');

  Route::resource('/sliders', 'SlidersController');
  //Cargar imagen de producto
  Route::post('image','SlidersController@images')->name('sliders.images');
  //modificar slider
  Route::post('/editar-slider/{id}', 'SlidersController@edit')->name('sliders.edit');
  Route::put('/eliminarSliders/{id}', 'SlidersController@eliminarSliders')->name('sliders.eliminarSliders');

  Route::resource('/contenido', 'ContenidoController');

  Route::get('modificarContenido', 'ContenidoController@modificarContenido')->name('contenido.modificarContenido');

  Route::post('modificarContenidoModal', 'ContenidoController@modificarContenidoModal')->name('contenido.modificarContenidoModal');

  Route::resource('/productos', 'ProductosController');

  Route::post('/productos-imagen', 'ProductosController@subirImagen')->name('productos.imagenes');
  //Borrar imagen
  Route::get('delete/{id}', 'ProductosController@destroy')->name('productos.delete');
  //Borrar color
  Route::get('deleteColor/{id}', 'ProductosController@deleteColor')->name('productos.deleteColor');
  //Borrar talles
  Route::get('/deleteTalles', 'ProductosController@deleteTalles')->name('productos.deleteTalles');


  Route::post('/productos-color', 'ProductosController@subirColor')->name('productos.color');

  Route::post('/productos-talles', 'ProductosController@subirTalles')->name('productos.talles');

  Route::get('/obtener-colores-tallas', 'ProductosController@getTallasColores')->name('productos.getColoresTallas');
  Route::post('/agregarTalla', 'ProductosController@agregarTalla')->name('productos.agregarTalla');

  Route::post('/modificar', 'ProductosController@modificar')->name('productos.modificar');

  Route::post('/modificarExistente', 'ProductosController@modificarExistente')->name('productos.modificarExistente');

  Route::get('pagination_productos', 'ProductosController@tablaProductos')->name('productos.tablaProductos');
  
  Route::get('buscarImagenModal', 'ProductosController@buscarImagen')->name('productos.buscarImagen');

  Route::get('borrarImagenModal', 'ProductosController@borrarImagen')->name('productos.borrarImagen');


  // Ordenar imagenes de productos
  Route::post('ordenarImagenProducto', 'ProductosController@ordenarImagenProducto')->name('productos.ordenarImagenProducto');
  // Habilitar color
  Route::post('habilitarColor', 'ProductosController@habilitarColor')->name('productos.habilitarColor');

  //Modificar Usuario
  Route::post('modificar_usuarioUsuario', 'UsuarioController@modificar_usuarioUsuario')->name('usuario.modificar_usuarioUsuario');

  Route::get('verCurriculum', 'curriculumController@verCurriculum')->name('curriculum.verCurriculum');
  Route::get('eliminarCurriculum', 'curriculumController@eliminarCurriculum')->name('curriculum.eliminar');

  Route::post('agregarEmpleo', 'curriculumController@agregarEmpleo')->name('curriculum.agregarEmpleo');

  Route::post('editarEmpleo', 'curriculumController@editarEmpleo')->name('curriculum.editarEmpleo');

  Route::get('divisas', 'ContenidoController@verDivisas')->name('divisa.verDivisas');

  Route::post('agregarDivisa', 'ContenidoController@agregarDivisa')->name('divisa.agregarDivisa');

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;
use App\User;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\DB;

class UsuarioController extends Controller
{
  /**
 * Create a new controller instance.
 *
 * @return void
 */
  public function __construct()
  {
      $this->middleware('auth');
  }

  public function index(Request $request)
  {
     $user = User::All();
     $id = '';
     if ($request->name) { $id = $request->id; };

     return view('usuario.index', compact('user', 'id'));

  }

  public function show()
  {

  }

  public function store(Request $request)
  {

    Log::info("UsuarioController:store", ["request" => $request->all()]);

    $user = new User();
    $user->name = $request->nombre;
    $user->email = $request->email;
    $user->password = bcrypt($request->password);
    $user->razon_users = $request->razon;
    $user->ruc_users = $request->ruc;
    $user->direccion_users = $request->direccion;
    $user->telefono_users = $request->telefono;
    $user->perfil_users = "usuario";
    $user->estado_users = "activo";

    $user->save();

    DB::commit();

    return redirect()->route('usuario.index');
  }

  public function modificar_usuarioUsuario(Request $request) 
  {
    $u = User::whereid($request->id)->firstOrFail();
    $u->name = $request->nombre;
    $u->email = $request->email;
    $u->razon_users = $request->razon;
    $u->ruc_users = $request->ruc;
    $u->direccion_users = $request->direccion;
    $u->telefono_users = $request->telefono;
    $u->password = bcrypt($request->pass);
    $u->save();
  }

  
}

resources/views/usuario/index.blade.php
@extends('layouts.app')

@section('content')

<!-- Breadcrumb-->
<div class="breadcrumb-holder">
  <div class="container-fluid">
    <ul class="breadcrumb">
      <li class="breadcrumb-item"><a href="index.html">Home</a></li>
      <li class="breadcrumb-item active">Usuarios</li>
    </ul>
  </div>
</div>

<section>
  <div class="col-sm-12" style="padding: 10px;">
    <div class="row">
      <div class="col-lg-4">
        <div class="card">
          <div class="card-header">
            <div class="card-body" style="padding: 0;">
              <form action="{{route('usuario.store')}}" method="POST" role="form">
                @csrf
                <div class="form-group">
                  <label for="inlineFormInput">Nombre y apellido</label>
                  <input name="nombre" type="text" placeholder="Ej. Juan Perez" class="mr-3 form-control" style="width: 100%;">
                </div>

                <div class="form-group">
                  <label for="inlineFormInput">Razon Social</label>
                  <input name="razon" type="text" placeholder="Ej. Brabus S.A." class="mr-3 form-control" style="width: 100%;">
                </div>

                <div class="form-group">
                  <label for="inlineFormInput">Ruc / C.I.no.</label>
                  <input name="ruc" type="text" placeholder="Ej. 3456456-0" class="mr-3 form-control" style="width: 100%;">
                </div>

                <div class="form-group">
                  <label for="inlineFormInput">Dirección</label>
                  <input name="direccion" type="text" placeholder="Ej. Pizzaro 912" class="mr-3 form-control" style="width: 100%;">
                </div>

                <div class="form-group">
                  <label for="inlineFormInput">Teléfono</label>
                  <input name="telefono" type="text" placeholder="Ej. +595 981 456 456" class="mr-3 form-control" style="width: 100%;">
                </div>

                <div class="form-group">
                  <label for="inlineFormInput">E-mail</label>
                  <input name="email" type="email" placeholder="Ej. juan@namopua.com" class="mr-3 form-control" style="width: 100%;">
                </div>

                <div class="form-group">
                  <label for="inlineFormInput">Contraseña</label>
                  <input name="password" type="password" class="mr-3 form-control" style="width: 100%;">
                </div>

                <div class="form-group">
                  <label for="inlineFormInput">Confirma contraseña</label>
                  <input name="password-confirm" type="password" class="mr-3 form-control" style="width: 100%;">
                </div>

                <div class="form-group">
                  <button type="submit" class="mr-3 btn btn-primary">Agregar</button>
                </div>
              </form>
            </div>
          </div>

        </div>
      </div>

      <div class="col-lg-8">
        <div class="card">
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Nombre</th>
                    <th>Email</th>
                    <th>Razon Social</th>
                    <th>Ruc</th>
                    <th>Dirección</th>
                    <th>Teléfono</th>
                    <th>Perfil</th>
                    <th>Estado</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody class="table_usuario">
                  @foreach($user as $u)
                  @if($u->perfil_users == "usuario")
                  <tr>
                    <td>{{$u->id}}</td>
                    <td>{{$u->name}}</td>
                    <td>{{$u->email}}</td>
                    <td>{{$u->razon_users}}</td>
                    <td>{{$u->ruc_users}}</td>
                    <td>{{$u->direccion_users}}</td>
                    <td>{{$u->telefono_users}}</td>
                    <td>{{$u->perfil_users}}</td>
                    <td>{{$u->estado_users}}</td>
                    <td><button onclick="modificar_usuario('{{ $u->id }}', 
                                                           '{{ $u->name }}',
                                                           '{{ $u->email }}',
                                                           '{{ $u->razon_users }}', 
                                                           '{{ $u->ruc_users }}',
                                                           '{{ $u->direccion_users }}', 
                                                           '{{ $u->telefono_users }}', 
                                                           '{{ $u->password }}')" data-toggle="modal" data-target="#modal_editar_usuario" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i></button></td>
                  </tr>
                  @endif
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="modal fade" id="modal_editar_usuario">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="text-align: left;">
        <span>Codigo: <span id="codigo_usuario_modal"></span> Usuario: <span id="nombre_usuario_modal_titulo"></span></span>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <div class="col-12">
            <label>Nombre</label>
            <input type="hidden" class="form-control" id="id_usuario_modal">
            <input type="text" id="nombre_usuario_modal" class="form-control">
          </div>
          <div class="col-12">
            <label>Correo Electrónico</label>
            <input type="text" id="email_usuario_modal" class="form-control">
          </div>
          <div class="col-12">
            <label>Razón Social</label>
            <input type="text" id="razon_usuario_modal" class="form-control">
          </div>
          <div class="col-12">
            <label>RUC</label>
            <input type="text" id="ruc_usuario_modal" class="form-control">
          </div>
          <div class="col-12">
            <label>Dirección</label>
            <input type="text" id="direccion_usuario_modal" class="form-control">
          </div>
          <div class="col-12">
            <label>Teléfono</label>
            <input type="text" id="telefono_usuario_modal" class="form-control">
          </div>
          <div class="col-12">
            <label>Contraseña</label>
            <input type="password" id="pass_usuario_modal" class="form-control">
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" onclick="btn_modificar_usuario()">Modificar</button>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function modificar_usuario(id, nombre, email, razon, ruc, direccion, telefono, pass) {
    $('#id_usuario_modal').val(id);
    $('#nombre_usuario_modal').val(nombre);
    $('#email_usuario_modal').val(email);
    $('#razon_usuario_modal').val(razon);
    $('#ruc_usuario_modal').val(ruc);
    $('#direccion_usuario_modal').val(direccion);
    $('#telefono_usuario_modal').val(telefono);
    $('#pass_usuario_modal').val(pass);
    $('#nombre_usuario_modal_titulo').html(nombre);
    $('#codigo_usuario_modal').html(id);
  }

  function btn_modificar_usuario() {
    var id = $('#id_usuario_modal').val();
    var nombre = $('#nombre_usuario_modal').val();
    var email = $('#email_usuario_modal').val();
    var razon = $('#razon_usuario_modal').val();
    var ruc = $('#ruc_usuario_modal').val();
    var direccion = $('#direccion_usuario_modal').val();
    var telefono = $('#telefono_usuario_modal').val();
    var pass = $('#pass_usuario_modal').val();
    $.ajax({
      type:"ajax",
      url: "{{route('usuario.modificar_usuarioUsuario')}}",
      type: 'POST',
      data: { id: id, 
              nombre: nombre, 
              email: email, 
              razon: razon, 
              ruc: ruc,
              direccion: direccion, 
              telefono: telefono, 
              pass: pass,
              _token:'{{csrf_token()}}'},

      success: function(){
        location.reload();
      }
    });
  }
// function agregar_marcas() {
//   var nombre = document.getElementById("nombre").value;
//   var id_stock="";
//   console.log(nombre);
//   $.ajax({
//     type:"ajax",
//     url: "{{route('marcas.store')}}",
//     type: 'POST',
//     data: {nombre: nombre, _token:'{{csrf_token()}}'},
//
//     success: function(){
//
//       // var categoria = $(this).val();
//     $.get('/tabla_marcas', function(data){
// //esta el la peticion get, la cual se divide en tres partes. ruta,variables y funcion
//       console.log(data);
//       for (var i=0; i<data.length;i++)
//       id_stock+= '<tr>'+
//                  '<td>'+data[i].id_marcas+'</td>'+
//                  '<td contenteditable="true" class="column_name_marcas" data-column_name="nombre_marcas" data-id="'+data[i].id_marcas+'">'+data[i].nombre_marcas+'</td>'+
//                  '</tr>',
//
//                  $(".table_marcas").empty();
//                  $('.table_marcas').append(id_stock);
//          })
//
//
//     }
//   })
// };

</script>

@endsection