routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::bind('productos', function($slug){
//   return App\Productos::where('id_productos', $slug)->first();
// });

// Route::get('/', function () {
//     return view('guest.index');
// });

Route::get('/', 'GuestController@index')->name('guest');

Route::resource('/login', 'LoginController');

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::get('/home', 'HomeController@index')->name('home');
//front
Route::resource('/guest', 'GuestController');
//vista de historial de clientes
Route::get('/historial', 'GuestController@historial')->name('guest.historial');
//vista de historial de clientes
Route::get('/micuenta', 'GuestController@micuenta')->name('guest.micuenta');
//vista de historial de clientes
Route::get('/buscarDetallePedido', 'GuestController@buscarDetallePedido')->name('guest.buscarDetallePedido');
//enviar comprobante en historia
Route::post('/agregarComprobacion', 'GuestController@agregarComprobacion')->name('guest.agregarComprobacion');
//autocompletar buscador en header
Route::post('autocompletarInput', 'GuestController@autocompletarInput')->name('guest.autocompletarInput');
Auth::routes();

Route::resource('/shop', 'ShopController');
Route::get('/get-chunk-products', 'ShopController@getChunk')->name('shop.get.chunk');
Route::get('/shop/{id}', 'ShopController@show')->name('shop.producto');

Route::get('/shop/categorias/{id}', 'ShopController@categorias')->name('shop.categorias');

Route::get('/shop/subcategorias/{id}', 'ShopController@subcategorias')->name('shop.subcategorias');

Route::get('/shop/marcas/{id}', 'ShopController@marcas')->name('shop.marcas');

Route::get('/premium', 'ShopController@premium')->name('shop.premium');

Route::get('/lanzamientos', 'ShopController@lanzamientos')->name('shop.lanzamientos');

Route::get('/ofertas', 'ShopController@ofertas')->name('shop.ofertas');

Route::get('/busqueda', 'ShopController@genero')->name('shop.genero');
// Actualizar caja de imagenes en shop productos unitarios
Route::get('BuscarShopGenero/{genero}', 'ShopController@BuscarShopGenero')->name('shop.BuscarShopGenero');
// Actualizar caja de imagenes en shop productos para genero y id_subcategorias
Route::get('BuscarShopGeneroMain/{genero}/{id}', 'ShopController@BuscarShopGeneroMain')->name('shop.BuscarShopGeneroMain');
// Actualizar caja de imagenes en shop productos unitarios
Route::get('busqueda_imagenes/{color}/{productos}', 'ShopController@BuscarImagenes');


//Shop Olimpia
Route::get('/TiendaOlimpia', 'ShopController@tiendaOlimpia')->name('shop.tiendaOlimpia');


//Carrito
Route::get('/cart/show', 'ShopController@sesion');
//agregar item al carrito
Route::get('cart/add/{id}','ShopController@add');
//buscar producto para front.php
Route::get('busquedaProductos','GuestController@buscarProducto')->name('guest.buscarProducto');
//agregar carrito por ajax desde vista de productos
Route::get('agregarCarrito', 'ShopController@agregarCarrito')->name('carrito.agregarCarrito');
//remover carrito por ajax desde vista de productos
Route::get('removerItemCarrito', 'ShopController@removerItemCarrito')->name('carrito.removerItemCarrito');
//vista de contactos
Route::resource('/contactos', 'ContactosController');

Route::resource('/carrito', 'CarritoController');

Route::resource('/caja', 'CajaController');
//realizar pedido
Route::post('/agregarFactura', 'CajaController@agregarFactura')->name('caja.agregarFactura');
//buscar ultima factura
Route::get('/buscarFacturaLast', 'CajaController@buscarFacturaLast')->name('caja.buscarFacturaLast');
//buscar factura para desplegar en vista
Route::get('/buscarFactura', 'CajaController@buscarFactura')->name('caja.buscarFactura');
//agregar direccion de envio
Route::post('/direccionEnvio', 'CajaController@direccionEnvio')->name('caja.direccionEnvio');
//buscar ultima factura
Route::get('/buscarDireccionEnvioLast', 'CajaController@buscarDireccionEnvioLast')->name('caja.buscarDireccionEnvioLast');
//buscar direccion de envio para vista de caja
Route::get('/buscarDireccionEnvio', 'CajaController@buscarDireccionEnvio')->name('caja.buscarDireccionEnvio');
//realizar pedido
Route::post('/realizarPedido', 'CajaController@realizarPedido')->name('caja.realizarPedido');
//realizar pedido
Route::get('/pedidoFinalizado', 'CajaController@pedidoFinalizado')->name('caja.pedidoFinalizado');
//vista terminos y condiciones
Route::get('/terminos_y_condiciones', 'GuestController@terminosCondiciones')->name('guest.terminosCondiciones');
//vista nosotros
Route::get('/nosotros', 'GuestController@nosotros')->name('guest.nosotros');
//vista trabaje con nosotros
Route::get('/trabaje_con_nosotros', 'GuestController@trabajeConNosotros')->name('guest.trabajeConNosotros');
//Busqueda de requisitos de empleo 
Route::get('/buscarEmpleo', 'GuestController@buscarEmpleo')->name('guest.buscarEmpleo');

Route::post('/agregarEmpleoGuest', 'GuestController@agregarEmpleoGuest')->name('guest.agregarEmpleoGuest');

Route::get('exportacion', 'GuestController@vistaExportacion')->name('guest.vistaExportacion');

Route::post('agregarExportacion', 'GuestController@agregarExportacion')->name('guest.agregarExportacion');


Route::group(['middleware' => ['auth']], function () {

  Route::post('/editar-datos', 'GuestController@editar_datos')->name('guest.editar.datos');

  //buscar detalle de pedido
  Route::get('/enviarDetalle', 'HomeController@enviarDetalle')->name('admin.enviarDetalle');
  //buscar comprobante de pedido
  Route::get('/enviarComprobante', 'HomeController@enviarComprobante')->name('admin.enviarComprobante');
  //descargar pdf de detalle
  Route::post('/descargar-pdf', 'HomeController@descargarPDF')->name('admin.descargarDetallesPDF');
  //modificar proceso
  Route::get('/modificarProceso', 'HomeController@modificarProceso')->name('admin.modificarProceso');

  Route::post('logout', 'Auth\LoginController@logout')->name('logout');
  //front
  Route::resource('/usuario', 'UsuarioController');
  //categorias
  Route::resource('/categorias', 'CategoriasController');
  // Actualizar tabla despues de insercion de categorias
  Route::get('tabla_categorias', 'CategoriasController@categoriaBuscar');
  //subcategorias
  Route::resource('/subcategorias', 'SubCategoriasController');
  // Actualizar tabla despues de insercion de subcategorias
  Route::get('tabla_subcategorias', 'SubCategoriasController@subcategoriaBuscar');
  //Marcas
  Route::resource('/marcas', 'MarcasController');
  //Productos
  Route::resource('/productos', 'ProductosController');
  // Actualizar tabla despues de insercion de subcategorias
  Route::get('tabla_marcas', 'MarcasController@MarcasBuscar');

  Route::resource('/color', 'ColorController');
  // Actualizar tabla despues de insercion de subcategorias
  Route::get('tabla_color', 'ColorController@ColorBuscar');

  Route::post('/agregarColor', 'ProductosController@agregarColor')->name('productos.agregarColor');

  Route::resource('/talles', 'TallesController');
  // Actualizar tabla despues de insercion de subcategorias
  Route::get('tabla_talles', 'TallesController@TallesBuscar');

  Route::resource('/secciones', 'SeccionesController');
  // Actualizar tabla despues de insercion de subcategorias
  Route::get('tabla_secciones', 'SeccionesController@SeccionesBuscar');

  Route::resource('/sliders', 'SlidersController');
  //Cargar imagen de producto
  Route::post('image','SlidersController@images')->name('sliders.images');
  //modificar slider
  Route::post('/editar-slider/{id}', 'SlidersController@edit')->name('sliders.edit');
  Route::put('/eliminarSliders/{id}', 'SlidersController@eliminarSliders')->name('sliders.eliminarSliders');

  Route::resource('/contenido', 'ContenidoController');

  Route::get('modificarContenido', 'ContenidoController@modificarContenido')->name('contenido.modificarContenido');

  Route::post('modificarContenidoModal', 'ContenidoController@modificarContenidoModal')->name('contenido.modificarContenidoModal');

  Route::resource('/productos', 'ProductosController');

  Route::post('/productos-imagen', 'ProductosController@subirImagen')->name('productos.imagenes');
  //Borrar imagen
  Route::get('delete/{id}', 'ProductosController@destroy')->name('productos.delete');
  //Borrar color
  Route::get('deleteColor/{id}', 'ProductosController@deleteColor')->name('productos.deleteColor');
  //Borrar talles
  Route::get('/deleteTalles', 'ProductosController@deleteTalles')->name('productos.deleteTalles');


  Route::post('/productos-color', 'ProductosController@subirColor')->name('productos.color');

  Route::post('/productos-talles', 'ProductosController@subirTalles')->name('productos.talles');

  Route::get('/obtener-colores-tallas', 'ProductosController@getTallasColores')->name('productos.getColoresTallas');
  Route::post('/agregarTalla', 'ProductosController@agregarTalla')->name('productos.agregarTalla');

  Route::post('/modificar', 'ProductosController@modificar')->name('productos.modificar');

  Route::post('/modificarExistente', 'ProductosController@modificarExistente')->name('productos.modificarExistente');

  Route::get('pagination_productos', 'ProductosController@tablaProductos')->name('productos.tablaProductos');
  
  Route::get('buscarImagenModal', 'ProductosController@buscarImagen')->name('productos.buscarImagen');

  Route::get('borrarImagenModal', 'ProductosController@borrarImagen')->name('productos.borrarImagen');


  // Ordenar imagenes de productos
  Route::post('ordenarImagenProducto', 'ProductosController@ordenarImagenProducto')->name('productos.ordenarImagenProducto');
  // Habilitar color

app/subcategorias.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Log;

class subcategorias extends Model
{
  protected $table = 'subcategorias';

  protected $primaryKey = 'id_subcategorias';
  /**
  * The attributes that are mass assignable.
  *
  * @var array
  */
  protected $fillable = [
    'id_subcategorias',
    'nombre_subcategorias',
    'pk_categorias_subcategorias',
    'active_subcategorias',
    'created_subcategorias'
  ];

  public static function filterAndPaginatePatients($name)
  {
    $rowsPerPage = 5;

    return  subcategorias::name($name)
        ->orderBy('id_subcategorias')
        ->where('active_subcategorias', true)
  //            ->paginate($rowsPerPage);
        ->get();
  }

  public function scopeName($query, $name)
  {
    if($name){
        return $query->where('nombre_subcategorias', 'ilike', '%'.$name.'%');
    }
  }

  public static function getAll()
  {
    return DB::table('subcategorias')
    ->join('categorias', 'categorias.id_categorias', 'subcategorias.pk_categorias_subcategorias')->get();
  }

  // public static function con_productosBk($tipo){
  //   $subcategorias = DB::table('subcategorias')->join('productos', 'productos.pk_subcategorias_productos', 'subcategorias.id_subcategorias')->where('tipo_producto', $tipo)->get()->toArray();
  //   $subcategorias = array_unique(array_column($subcategorias, 'nombre_subcategorias'));
  //   $subcategoriasid = array_unique(array_column($subcategorias, 'id_subcategorias'));
  //   foreach ($subcategoriasid as $subcate) {
  //   }
  //   return $subcategorias;
  // }
  public function con_productos(){
    return $this->hasMany(Productos::class, 'pk_subcategorias_productos', 'id_subcategorias');
  }

  public static function subProdutos()
  {
    return DB::table('subcategorias')
    ->select('nombre_subcategorias', 'tipo_producto', 'id_subcategorias')
    ->distinct()
    ->where('active_subcategorias', true)
    ->join('productos', 'productos.pk_subcategorias_productos', 'subcategorias.id_subcategorias')
    ->orderBy('nombre_subcategorias', 'ASC')
    ->get();
  }
}

app/Http/Controllers/SubCategoriasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;
use App\categorias;
use App\subcategorias;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\DB;

class SubCategoriasController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $subcategory = subcategorias::filterAndPaginatePatients($request->id_subcategorias);
        $id = '';
        if ($request->name) {
            $id = $request->id_subcategorias;
        };
        $categoria = categorias::where('active_categorias', true)->get();
        $subActive = DB::table('subcategorias')->where('active_subcategorias', true)
        ->join('categorias', 'categorias.id_categorias', 'subcategorias.pk_categorias_subcategorias')
        ->get();
        $subInactive = DB::table('subcategorias')->where('active_subcategorias', false)
        ->join('categorias', 'categorias.id_categorias', 'subcategorias.pk_categorias_subcategorias')
        ->get();

        return view('subcategorias.index', compact('subActive', 'subInactive', 'subcategory', 'id', 'categoria'));
    }

    public function show()
    {
    }

    public function store(Request $request)
    {

        $insert = DB::table('subcategorias')
            ->insert([
                'nombre_subcategorias' => $request->nombre,
                'pk_categorias_subcategorias' => $request->categoria,
                'active_subcategorias' => 1,
                'created_subcategorias' => auth()->user()->id
            ]);
        return response()->json($insert);
    }

    public function subcategoriaBuscar()
    {
        return DB::table('subcategorias')
            ->join('categorias', 'categorias.id_categorias', 'subcategorias.pk_categorias_subcategorias')
            ->orderBy('id_subcategorias', 'ASC')
            ->get();
    }

    public function edit($id)
    {
        $category = subcategorias::findOrFail($id);
        $cat = categorias::where('active_categorias', true)->get();
        return view('subcategorias.edit', compact('category', 'cat'));
    }

    public function update(Request $request, $slug)
    {
        if (isset($request->nuevo_estado)) {
            DB::table('subcategorias')->where('id_subcategorias', $slug)->update(['active_subcategorias' => $request->nuevo_estado]);
            $response['success'] = true;
            $response['data'] = DB::table('subcategorias')
            ->join('categorias', 'categorias.id_categorias', 'subcategorias.pk_categorias_subcategorias')
            ->where('id_subcategorias', $slug)->first();
            return response()->json($response);
        } else {
            $categoryEdit = subcategorias::whereid_subcategorias($slug)->firstOrFail();
            $categoryEdit->nombre_subcategorias = $request->nombre_subcategorias;
            $categoryEdit->pk_categorias_subcategorias = $request->pk_categorias_subcategorias;
            $categoryEdit->save();
            return redirect()->route('subcategorias.index');
        }
    }
}

resources/views/subcategorias/edit.blade.php
@extends('layouts.app')

@section('content')

<!-- Breadcrumb-->
<div class="breadcrumb-holder">
  <div class="container-fluid">
    <ul class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item"><a href="/subcategorias">Sub categorias</a></li>
      <li class="breadcrumb-item active">Editar</li>
    </ul>
  </div>
</div>

<section>
  <div class="col-sm-12" style="padding: 10px;">
    <div class="row">
      <div class="col-lg-5">
        <div class="card">
          <div class="card-body">
            <form action="{{url('/subcategorias/'. $category->id_subcategorias)}}" method="POST" role="form">
              @csrf
              @method('PATCH')
              <div class="form-group">
                <label for="inlineFormInput" class="sr-only">Agregar sub categorias</label>
                <input id="nombre" name="nombre_subcategorias" type="text" placeholder="Nombre de subcategoria" class="mr-3 form-control" value="{{$category->nombre_subcategorias}}">
              </div>
              <div class="form-group">
                <select id="categoria" name="pk_categorias_subcategorias" class="mr-3 form-control" style="width: 100%">
                  @foreach($cat as $c)
                  @if($c->id_categorias == $category->pk_categorias_subcategorias)
                  <option value="{{$c->id_categorias}}">{{$c->nombre_categorias}}</option>
                  @endif
                  @endforeach

                  @foreach($cat as $ca)
                  <option value="{{$ca->id_categorias}}">{{$ca->nombre_categorias}}</option>
                  @endforeach
                </select>
              </div>
              <div class="form-group">
                <button type="submit" class="mr-3 btn btn-primary">Modificar</button>
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

@endsection

resources/views/subcategorias/index.blade.php
@extends('layouts.app')

@section('content')
    <!-- Breadcrumb-->
    <div class="breadcrumb-holder">
        <div class="container-fluid">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item active">Sub Categorias</li>
            </ul>
        </div>
    </div>

    <section>
        <div class="col-sm-12" style="padding: 10px;">
            <div class="row">
                <div class="col-lg-5">
                    {{-- formulario de agregar --}}
                    <div class="card">
                        <div class="card-header">
                            <div class="card-body" style="padding: 0;">
                                <div class="form-inline">
                                    @csrf
                                    <div class="form-group">
                                        <label for="inlineFormInput" class="sr-only">Agregar sub categorias</label>
                                        <input id="nombre" type="text" placeholder="Nombre de subcategoria"
                                            class="mr-3 form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="inlineFormInput" class="sr-only">Categorias</label>
                                        <select id="categoria" class="mr-3 form-control" style="width: 200px;">
                                            <option selected disabled>Categoria...</option>
                                            @foreach ($categoria as $cat)
                                                <option value="{{ $cat->id_categorias }}">{{ $cat->nombre_categorias }}
                                                </option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <button onclick="agregar_subcategorias()"
                                            class="mr-3 btn btn-primary">Agregar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {{-- <div class="card-body">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Nombre</th>
                                            <th>Categoria</th>
                                            <th>Accion</th>
                                        </tr>
                                    </thead>
                                    <tbody class="table-subcategorias">
                                        @foreach ($sub as $su)
                                            <tr>
                                                <th scope="row">{{ $su->id_subcategorias }}</th>
                                                <td>{{ $su->nombre_subcategorias }}</td>
                                                <td>{{ $su->nombre_categorias }}</td>
                                                <td>
                                                    <a href="{{ route('subcategorias.edit', $su->id_subcategorias) }}">
                                                        <i class="icon-form"></i>
                                                    </a>
                                                    &nbsp;
                                                    &nbsp;
                                                    &nbsp;
                                                    <i class="fa fa-arrow-right cambiar_estado"
                                                        data-nuevo-estado="{{ $su->active_subcategorias }}"
                                                        data-colum-name="active_subcategorias"></i>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div> --}}
                    </div>
                </div>
            </div>
            <div class="row">

                <div class="col-lg-5 col-sm-12">
                    {{-- tabla de subcategorias activas --}}
                    <div class="card">
                        <div class="card-header">
                            Activos
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Nombre</th>
                                            <th>Categoria</th>
                                            <th>Accion</th>
                                        </tr>
                                    </thead>
                                    <tbody class="table-subcategorias" id="activas">
                                        @foreach ($subActive as $su)
                                            <tr data-id="{{ $su->id_subcategorias }}">
                                                <th scope="row">{{ $su->id_subcategorias }}</th>
                                                <td>{{ $su->nombre_subcategorias }}</td>
                                                <td>{{ $su->nombre_categorias }}</td>
                                                <td>
                                                    <a href="{{ route('subcategorias.edit', $su->id_subcategorias) }}">
                                                        <i class="icon-form"></i>
                                                    </a>
                                                    &nbsp;
                                                    &nbsp;
                                                    &nbsp;
                                                    <i class="fa fa-arrow-right cambiar_estado p-1"
                                                        data-id="{{ $su->id_subcategorias }}"
                                                        data-nuevo-estado="false"
                                                        data-column-name="active_subcategorias"></i>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 col-sm-12">
                    {{-- tabla de subcategorias inactivas --}}
                    <div class="card">
                        <div class="card-header">
                            Inactivos
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Nombre</th>
                                            <th>Categoria</th>
                                            <th>Accion</th>
                                        </tr>
                                    </thead>
                                    <tbody class="table-subcategorias" id="inactivas">
                                        @foreach ($subInactive as $su)
                                            <tr data-id="{{ $su->id_subcategorias }}">
                                                <th scope="row">{{ $su->id_subcategorias }}</th>
                                                <td>{{ $su->nombre_subcategorias }}</td>
                                                <td>{{ $su->nombre_categorias }}</td>
                                                <td>
                                                    <a href="{{ route('subcategorias.edit', $su->id_subcategorias) }}">
                                                        <i class="icon-form"></i>
                                                    </a>
                                                    &nbsp;
                                                    &nbsp;
                                                    &nbsp;
                                                    <i class="fa fa-arrow-left cambiar_estado p-1"
                                                        data-id="{{ $su->id_subcategorias }}"
                                                        data-nuevo-estado="true"
                                                        data-column-name="active_subcategorias"></i>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script>
        const url_tabla = "/subcategorias/"

        function agregar_subcategorias() {
            var nombre = document.getElementById("nombre").value;
            var categoria = document.getElementById("categoria").value;
            var id_stock = "";
            console.log(nombre);
            console.log(categoria);
            $.ajax({
                type: "ajax",
                url: "{{ route('subcategorias.store') }}",
                type: 'POST',
                data: {
                    nombre: nombre,
                    categoria: categoria,
                    _token: '{{ csrf_token() }}'
                },

                success: function() {

                    location.reload();

                }
            })
        };

        function nuevaFilaEstado(data) {
            let arrow = ""
            let nuevoEstado
            let fila = ""
            if (data.active_subcategorias) {
                arrow = "right"
                nuevoEstado = "false"
            } else {
                arrow = "left"
                nuevoEstado = "true"
            }
            fila = `
              <tr data-id="${data.id_subcategorias}">
                  <th scope="row">${data.id_subcategorias}</th>
                  <td>${data.nombre_subcategorias}</td>
                  <td>${data.nombre_categorias}</td>
                  <td>
                      <a href="/subcategorias/${data.id_subcategorias}/edit">
                          <i class="icon-form"></i>
                      </a>
                      &nbsp;
                      &nbsp;
                      &nbsp;
                      <i class="fa fa-arrow-${arrow} cambiar_estado p-1"
                          data-id="${data.id_subcategorias}"
                          data-nuevo-estado="${nuevoEstado}"
                          data-column-name="active_subcategorias"></i>
                  </td>
              </tr>
            `;
            //se agrega la nueva fila a la tabla activos o inactivos
            if (data.active_subcategorias) {
              $("#activas").append(fila)
            } else {
              $("#inactivas").append(fila)
            }
        }
    </script>

@endsection